// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ApiTestAutomationProject.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Post Update Operations")]
    [NUnit.Framework.CategoryAttribute("Feature:PostUpdate")]
    [NUnit.Framework.CategoryAttribute("Target:API")]
    [NUnit.Framework.CategoryAttribute("need")]
    public partial class PostUpdateOperationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "Feature:PostUpdate",
                "Target:API",
                "need"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Post Update Operations", "    Tests for Post Update operations using ReqRes API", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update post and verify the updated post")]
        [NUnit.Framework.CategoryAttribute("PostUpdate")]
        [NUnit.Framework.CategoryAttribute("need:update")]
        [NUnit.Framework.TestCaseAttribute("Valid", "Valid", "Updated", null)]
        [NUnit.Framework.TestCaseAttribute("Valid2", "Valid", "Updated", null)]
        public void UpdatePostAndVerifyTheUpdatedPost(string postType, string updateType, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PostUpdate",
                    "need:update"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("postType", postType);
            argumentsOfScenario.Add("updateType", updateType);
            argumentsOfScenario.Add("result", result);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update post and verify the updated post", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is logged in with valid credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.And(string.Format("a post exists with {0}", postType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                testRunner.When(string.Format("the post is updated with {0}", updateType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.And("the updated post is retrieved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                testRunner.Then(string.Format("the post update is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
                testRunner.And("the retrieved post matches the updated data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update post with invalid data (ReqRes API accepts all data)")]
        [NUnit.Framework.CategoryAttribute("PostUpdate")]
        [NUnit.Framework.CategoryAttribute("need:update")]
        [NUnit.Framework.TestCaseAttribute("Valid", "Invalid", "Updated", null)]
        [NUnit.Framework.TestCaseAttribute("Valid", "Empty", "Updated", null)]
        public void UpdatePostWithİnvalidDataReqResAPIAcceptsAllData(string postType, string updateType, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PostUpdate",
                    "need:update"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("postType", postType);
            argumentsOfScenario.Add("updateType", updateType);
            argumentsOfScenario.Add("result", result);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update post with invalid data (ReqRes API accepts all data)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("the user is logged in with valid credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
                testRunner.And(string.Format("a post exists with {0}", postType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
                testRunner.When(string.Format("the post is updated with {0}", updateType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
                testRunner.Then(string.Format("the post update is {0}", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
